item {
    id: 1
    name: 'Id'
}

item {
    id: 2
    name: 'Name'
}
item {
    id: 3
    name: 'Birth'
}

item {
    id: 4
    name: 'Sex'
}

item {
    id: 5
    name: 'Nationality'
}

item {
    id: 6
    name: 'Origin'
}

item {
    id: 7
    name: 'Residence'
}