item {
    id: 1
    name: 'id'
}

item {
    id: 2
    name: 'name'
}
item {
    id: 3
    name: 'dob'
}

item {
    id: 4
    name: 'sex'
}

item {
    id: 5
    name: 'nati'
}

item {
    id: 6
    name: 'pla'
}

item {
    id: 7
    name: 'res'
}

item {
    id: 8
    name: 'date'
}

